# holds the sticker server backend
service: server

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: prod

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.wisosim.com"
    stage: prod
    basePath: sticker
    certificateName: "*.wisosim.com"
    endpointType: edge

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get

